name: main

on:
  push:
    branches: [main, feat/*, bug/*]
    tags: v*
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**.md"
  workflow_dispatch:

jobs:
  dbc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip3 install -r requirements.txt
      - run: python generate-dbc.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dbc
          path: "*.dbc"

  release:
    needs: dbc
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts (dbc)
        uses: actions/download-artifact@v2
        with:
          name: dbc
          path: dbc

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes --repo $GITHUB_REPOSITORY $GITHUB_REF_NAME **/*.dbc
